### ISSUE TITLE
Order of included styles using styled-components

### ISSUE THREAD

**Issue by sandrig** [momesana/dynamic-antd-theme-demo#1]
I'm using styled-components, but when I change the theme, the new stylesheet with the theme is loaded at the very bottom of the head section.

I expect styled-components to always be at the bottom so that it doesn't break the current layout.

**Comment by momesana** [comment]
Hi @sandrig,
thanks for the feedback. You can of course fine-tune the position where the style is being inserted via the `insert` options of the styled-loader as described [here](https://webpack.js.org/loaders/style-loader/#function). The example in the documentation exactly describes the scenario you outlined above and instructs style-loader to apply the styles at the top of the `<header>` tag. 

Most of the times however, the order is only significant if two properties end up having the same [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) which is an undesirable constellation to begin with. Imho, the most straight-forward way to deal with this is to make sure your styled components have a higher specificity and thus win over the antd styles (or any other global style for that matter). This is a little difficult with antd,  especially if you are using the antd class names in your styled components to override the default styles. Still, even without using the above property In styled-components this can for example be achieved by manually increasing specificity as described [here](https://styled-components.com/docs/faqs#how-can-i-override-styles-with-higher-specificity):
```js
const MyStyledComponent = styled(AlreadyStyledComponent)`
  &&& {
    color: palevioletred;
    font-weight: bold;
  }
`
```
One could also use `!important` but that's generally regarded poor style.

There is more advice on that in the documentation:
https://styled-components.com/docs/advanced#issues-with-specificity
https://styled-components.com/docs/advanced#avoiding-conflicts-with-thirdparty-styles-and-scripts

**Comment by sandrig** [comment]
Hi, @momesana,
thanks for the answer. Solved the problem with by added lazySingletonStyleTag and insert styles before target element as described [here](https://webpack.js.org/loaders/style-loader/#function).
